# Generated by Django 4.0.1 on 2022-07-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='companies',
            field=models.ManyToManyField(related_name='problems', to='problems.Company'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='roles',
            field=models.ManyToManyField(related_name='problems', to='problems.Role'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subcategories',
            field=models.ManyToManyField(related_name='problems', to='problems.SubCategory'),
        ),
    ]
