# Generated by Django 4.0.1 on 2022-07-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_companies_alter_problem_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutput',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputoutputs', to='problems.problem'),
        ),
    ]
