# Generated by Django 4.0.1 on 2022-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_problem_companies_remove_problem_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.ManyToManyField(related_name='problems', to='problems.Company'),
        ),
    ]
