# Generated by Django 4.0.1 on 2022-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_roles_problem_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
