# Generated by Django 4.0.1 on 2022-08-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_problem_memory_limit_alter_problem_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(default='c', max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solve_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
