# Generated by Django 4.0.1 on 2022-08-26 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_alter_solution_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='date_added',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
