# Generated by Django 4.0.1 on 2022-08-26 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_remove_bookmark_date_added_bookmark_time_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
