# Generated by Django 4.0.1 on 2022-08-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_alter_bookmark_time_added_alter_solution_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='problems.problem'),
        ),
    ]
