# Generated by Django 4.0.1 on 2022-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_alter_bookmark_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutput',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
