# Generated by Django 4.0.1 on 2022-07-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_inputoutput_problem'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='roles',
            field=models.ManyToManyField(related_name='assessment', to='problems.Role'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subcategories',
            field=models.ManyToManyField(related_name='assessment', to='problems.SubCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='assessments.assessment'),
        ),
        migrations.DeleteModel(
            name='AssessQues',
        ),
    ]
