# Generated by Django 4.0.1 on 2022-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_roles_assessment_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
