# Generated by Django 4.0.1 on 2022-07-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_link',
        ),
    ]
