# Generated by Django 4.0.1 on 2022-07-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_inputoutput_problem'),
        ('assessments', '0005_remove_option_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='assessment',
            name='categories',
            field=models.ManyToManyField(related_name='assessment', to='problems.Category'),
        ),
    ]
