# Generated by Django 4.0.1 on 2022-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
