# Generated by Django 4.0.1 on 2022-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_comments_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
