# Generated by Django 4.0.1 on 2022-07-15 05:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0009_downvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
