# Generated by Django 4.0.1 on 2022-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_discussion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
