# Generated by Django 4.0.1 on 2022-08-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0012_commentupvoted_commentdownvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentupvoted',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentupvoted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='CommentDownvoted',
        ),
        migrations.DeleteModel(
            name='CommentUpvoted',
        ),
    ]
